favicon: null
name: Danielacaballero
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7640382
  brandStrength: 1
  lightness: 0.9504181
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#25272A'
    - '#A5A7AA'
    - '#616366'
  rhythmicContrast: 0.281362
typography_spectrum: 0.5167264
layout_spectrum: 0.4784946
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
